spring:
  application:
    name: mini-erp-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_erp
    username: mini_erp
    password: mini_erp_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080

app:
  cognito:
    issuer-uri: ${COGNITO_ISSUER_URI}
    client-id: ${COGNITO_USER_POOL_CLIENT_ID}
  docs:
    enabled: ${API_DOCS_ENABLED:false}

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${API_DOCS_ENABLED:false}
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
